### ISSUE TITLE
What is the line about FABRIC_ROOT

### ISSUE THREAD

**Issue by mitra42** [yeasy/docker-ipfs#2]
I'm unclear what the line `ENV FABRIC_ROOT=$GOPATH/src/github.com/hyperledger/fabric`
refers to since that project [https://github.com/hyperledger/fabric] doesn't seem to have anything to do with IPFS, the comment `Only useful for this Dockerfile` doesnt really help. 

If its necessary for your own project wouldnt it be better to build another docker `FROM` this one with the project specific env variables ?

**Comment by yeasy** [comment]
Correct, that line has no usage.
Would you like to help remove or let me do that?

**Comment by mitra42** [comment]
Pull request created. 

Note My version has diverged a long way from yours now, happy to share at any point, but needs wider testing before pushing back.   We addressed a number of issues in yours that IPFS's 'official' DOckerfile doesnt have, and vica-versa. 

We also based it FROM Ubuntu because we need other things in our Dockerfile, though the rest of the changes are just as relevant to your Dockerfile.

**Comment by yeasy** [comment]
Sure, welcome for feedbacks, thanks!
